# DAMR
Hi, here is the code of DAMR(Dynamic Ajacency Matrix Representation) 
for data imputation in airquality dataset.。

# 1. Import library

In [1]:
#1.Import library
import numpy as np
import pandas as pd
import datetime
import matplotlib.pyplot as plt
import networkx as nx
from networkx.algorithms import bipartite
import copy
from sklearn.preprocessing import StandardScaler
import scipy.special as special
import scipy.sparse as sp
import pickle
import os
from math import sqrt
from numpy import concatenate
from matplotlib import pyplot
from pandas import read_csv
from pandas import DataFrame
from pandas import concat
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

import tensorflow as tf
#import tensorflow_addons as tfa
import keras
from tensorflow.keras import backend as K
from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import Dense, GRU, Input
from tensorflow.keras.optimizers import SGD, Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import Input, Dropout, Dense, LeakyReLU, GRU, Concatenate, Reshape, Softmax, Attention
from tensorflow.keras import activations
from tensorflow.keras.models import Model
#from keras.layers import LeakyReLU
from spektral.layers import  GCSConv, DiffusionConv, GATConv, ARMAConv, GCNConv
from tensorflow.keras.regularizers import l2
#from my own library import Generate_missing and other models
from model import * #generate_miss(data,perc),output:data after generate missing.
import FancyImpute
from FancyImpute import *
import torch
#Bidirectional LSTM
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Bidirectional
from BiLSTM import BiLSTM_3D
import pickle

# 2. Data Pre-processing of COVID dataset


In [2]:
#Define hyperparameter
Miss_perc=0.1
Split_perc1=0.8
Split_perc2=0.1
data=Csv2Tensor('Data/AIRQUALITY/raw')
data=data[:503,:,:]
#Generate Missing 3D.
COVID_features=data
COVID_features=MinMax3D(COVID_features)#(503,6,10)
COVID_features_train=COVID_features[:int(Split_perc1*COVID_features.shape[0]),:,:]
print(COVID_features_train.shape)#(402, 6, 10)
COVID_features_val=COVID_features[int(Split_perc1*COVID_features.shape[0]):int(Split_perc1*COVID_features.shape[0])+int(Split_perc2*COVID_features.shape[0]),:,:]
print(COVID_features_val.shape)#(50, 6, 10)
COVID_features_test=COVID_features[int(Split_perc1*COVID_features.shape[0])+int(Split_perc2*COVID_features.shape[0]):,:,:]
print(COVID_features_test.shape)#(51, 6, 10)

#The mask and missing data has been created with a given miss percentage.
#It will be used for baseline and for DAMR
COVID_features_train_miss,COVID_features_train_mask=generate_miss_3D(COVID_features_train,Miss_perc)
COVID_features_val_miss,COVID_features_val_mask=generate_miss_3D(COVID_features_val,Miss_perc)
COVID_features_test_miss,COVID_features_test_mask=generate_miss_3D(COVID_features_test,Miss_perc)
COVID_features_miss,COVID_features_mask=generate_miss_3D(COVID_features,Miss_perc)


()
()
()
()
()
()
()
()
()
()
(402, 6, 10)
(50, 6, 10)
(51, 6, 10)


In [3]:
#BiLSTM_finish
COVID_features_miss,COVID_features_mask=generate_miss_3D(COVID_features,0.1)
BiLSTM_rmse,BiLSTM_mae,BiLSTM_mape,BiLSTM_mre,BiLSTM_err=BiLSTM_3D(COVID_features_miss,COVID_features,COVID_features_mask,0)
print("BiLSTM_rmse,",BiLSTM_rmse)
print("BiLSTM_mae",BiLSTM_mae)
print("BiLSTM_mape",BiLSTM_mape)
print("BiLSTM_mre",BiLSTM_mre)
print("BiLSTM_err",BiLSTM_err)

/Users/macbook/Desktop/PHD/CIKM/DAMR_CODE/FancyImpute.py:163: RuntimeWarning: divide by zero encountered in true_divide
  Sliding_mape= abs((np.array(Data_true)[missing_mask]-np.array(Data_Sliding)[missing_mask])/np.array(Data_true)[missing_mask]).mean()
/Users/macbook/Desktop/PHD/CIKM/DAMR_CODE/FancyImpute.py:163: RuntimeWarning: divide by zero encountered in true_divide
  Sliding_mape= abs((np.array(Data_true)[missing_mask]-np.array(Data_Sliding)[missing_mask])/np.array(Data_true)[missing_mask]).mean()
/Users/macbook/Desktop/PHD/CIKM/DAMR_CODE/FancyImpute.py:163: RuntimeWarning: divide by zero encountered in true_divide
  Sliding_mape= abs((np.array(Data_true)[missing_mask]-np.array(Data_Sliding)[missing_mask])/np.array(Data_true)[missing_mask]).mean()
/Users/macbook/Desktop/PHD/CIKM/DAMR_CODE/FancyImpute.py:163: RuntimeWarning: divide by zero encountered in true_divide
  Sliding_mape= abs((np.array(Data_true)[missing_mask]-np.array(Data_Sliding)[missing_mask])/np.array(Data_true)[mi

(402, 1, 6) (402, 6) (100, 1, 6) (100, 6)
Epoch 1/80
1/1 - 3s - loss: 0.5274 - val_loss: 0.5656
Epoch 2/80
1/1 - 0s - loss: 0.5195 - val_loss: 0.5575
Epoch 3/80
1/1 - 0s - loss: 0.5117 - val_loss: 0.5494
Epoch 4/80
1/1 - 0s - loss: 0.5040 - val_loss: 0.5414
Epoch 5/80
1/1 - 0s - loss: 0.4964 - val_loss: 0.5334
Epoch 6/80
1/1 - 0s - loss: 0.4889 - val_loss: 0.5255
Epoch 7/80
1/1 - 0s - loss: 0.4816 - val_loss: 0.5176
Epoch 8/80
1/1 - 0s - loss: 0.4744 - val_loss: 0.5098
Epoch 9/80
1/1 - 0s - loss: 0.4673 - val_loss: 0.5020
Epoch 10/80
1/1 - 0s - loss: 0.4604 - val_loss: 0.4942
Epoch 11/80
1/1 - 0s - loss: 0.4535 - val_loss: 0.4864
Epoch 12/80
1/1 - 0s - loss: 0.4468 - val_loss: 0.4786
Epoch 13/80
1/1 - 0s - loss: 0.4401 - val_loss: 0.4708
Epoch 14/80
1/1 - 0s - loss: 0.4335 - val_loss: 0.4631
Epoch 15/80
1/1 - 0s - loss: 0.4269 - val_loss: 0.4554
Epoch 16/80
1/1 - 0s - loss: 0.4204 - val_loss: 0.4478
Epoch 17/80
1/1 - 0s - loss: 0.4140 - val_loss: 0.4401
Epoch 18/80
1/1 - 0s - loss: 0.4

In [4]:
#Run baseline(KNN,MICE,MF,MEAN,SLIDING)#Return:RMSE,MAE,MAPE,MRE
#For the model of FancyImpute,we just need to test.
KNN_RMSE,KNN_MAE,KNN_MAPE,KNN_MRE=KNN_impute_3D(COVID_features_test_miss,COVID_features_test,COVID_features_test_mask)
MICE_RMSE,MICE_MAE,MICE_MAPE,MICE_MRE=MICE_impute_3D(COVID_features_test_miss,COVID_features_test,COVID_features_test_mask)
MF_RMSE,MF_MAE,MF_MAPE,MF_MRE=MF_impute_3D(COVID_features_test_miss,COVID_features_test,COVID_features_test_mask)
MEAN_RMSE,MEAN_MAE,MEAN_MAPE,MEAN_MRE=MEAN_impute_3D(COVID_features_test_miss,COVID_features_test,COVID_features_test_mask)
Sliding_RMSE,Sliding_MAE,Sliding_MAPE,Sliding_MRE,Sliding_out=Sliding_impute_3D(COVID_features_test_miss,COVID_features_test,COVID_features_test_mask,6)
print("KNN_RMSE",KNN_RMSE,"KNN_MAE",KNN_MAE,"KNN_MAPE",KNN_MAPE,"KNN_MRE",KNN_MRE)
print("MICE_RMSE",MICE_RMSE,"MICE_MAE",MICE_MAE,"MICE_MAPE",MICE_MAPE,"MICE_MRE",MICE_MRE)
print("MF_RMSE",MF_RMSE,"MF_MAE",MF_MAE,"MF_MAPE",MF_MAPE,"MF_MRE",MF_MRE)
print("MEAN_RMSE",MEAN_RMSE,"MEAN_MAE",MEAN_MAE,"MEAN_MAPE",MEAN_MAPE,"MEAN_MRE",MEAN_MRE)
print("Sliding_RMSE",Sliding_RMSE,"Sliding_MAE",Sliding_MAE,"Sliding_MAPE",Sliding_MAPE,"Sliding_MRE",Sliding_MRE)

Imputing row 1/51 with 0 missing, elapsed time: 0.001
Imputing row 1/51 with 0 missing, elapsed time: 0.002
Imputing row 1/51 with 1 missing, elapsed time: 0.001
Imputing row 1/51 with 1 missing, elapsed time: 0.001
Imputing row 1/51 with 0 missing, elapsed time: 0.001
Imputing row 1/51 with 0 missing, elapsed time: 0.001
Imputing row 1/51 with 0 missing, elapsed time: 0.001
Imputing row 1/51 with 0 missing, elapsed time: 0.001
Imputing row 1/51 with 0 missing, elapsed time: 0.001
Imputing row 1/51 with 0 missing, elapsed time: 0.001
                                     CVXPY                                     
                                     v1.2.0                                    
(CVXPY) May 28 04:17:27 PM: Your problem has 306 variables, 1 constraints, and 0 parameters.
(CVXPY) May 28 04:17:27 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 28 04:17:27 PM: (If you need to solve this problem multiple times, but with different data, consider using param

/opt/anaconda3/lib/python3.8/site-packages/sklearn/impute/_iterative.py:699: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(
/opt/anaconda3/lib/python3.8/site-packages/sklearn/impute/_iterative.py:699: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(


(CVXPY) May 28 04:17:27 PM: Applying reduction ConeMatrixStuffing
(CVXPY) May 28 04:17:27 PM: Applying reduction CVXOPT
(CVXPY) May 28 04:17:27 PM: Finished problem compilation (took 2.864e-02 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) May 28 04:17:27 PM: Invoking solver CVXOPT  to obtain a solution.
     pcost       dcost       gap    pres   dres   k/t
 0:  0.0000e+00 -3.0600e-02  5e+03  1e+01  5e+00  1e+00
 1:  1.6944e+01  1.8551e+01  1e+03  3e+00  1e+00  2e+00
 2:  1.6778e+01  1.7437e+01  2e+02  8e-01  3e-01  7e-01
 3:  1.6964e+01  1.7120e+01  5e+01  2e-01  8e-02  2e-01
 4:  1.6849e+01  1.6850e+01  1e+00  4e-03  2e-03  2e-03
 5:  1.6858e+01  1.6858e+01  1e-01  7e-04  3e-04  2e-05
 6:  1.6868e+01  1.6868e+01  5e-03  1e-04  4e-05  2e-05
 7:  1.6869e+01  1.6869e+01  8e-04  2

(CVXPY) May 28 04:17:38 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 28 04:17:38 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) May 28 04:17:38 PM: Compiling problem (target solver=CVXOPT).
(CVXPY) May 28 04:17:38 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> CVXOPT
(CVXPY) May 28 04:17:38 PM: Applying reduction Dcp2Cone
(CVXPY) May 28 04:17:38 PM: Applying reduction CvxAttr2Constr
(CVXPY) May 28 04:17:38 PM: Applying reduction ConeMatrixStuffing
(CVXPY) May 28 04:17:38 PM: Applying reduction CVXOPT
(CVXPY) May 28 04:17:38 PM: Finished problem compilation (took 3.075e-02 seconds).
----

(CVXPY) May 28 04:17:50 PM: Optimal value: 2.018e+01
(CVXPY) May 28 04:17:50 PM: Compilation took 3.507e-02 seconds
(CVXPY) May 28 04:17:50 PM: Solver (including time spent in interface) took 4.044e+00 seconds
                                     CVXPY                                     
                                     v1.2.0                                    
(CVXPY) May 28 04:17:50 PM: Your problem has 306 variables, 1 constraints, and 0 parameters.
(CVXPY) May 28 04:17:50 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) May 28 04:17:50 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) May 28 04:17:50 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
---------------------------------

 1:  1.8166e+01  1.9765e+01  1e+03  3e+00  1e+00  2e+00
 2:  1.8498e+01  1.9165e+01  2e+02  8e-01  3e-01  7e-01
 3:  1.8411e+01  1.8539e+01  4e+01  2e-01  7e-02  1e-01
 4:  1.8297e+01  1.8298e+01  8e-01  3e-03  1e-03  1e-03
 5:  1.8307e+01  1.8307e+01  8e-02  5e-04  2e-04  8e-06
 6:  1.8316e+01  1.8316e+01  4e-03  8e-05  3e-05  1e-05
 7:  1.8316e+01  1.8316e+01  8e-04  2e-05  7e-06  2e-06
 8:  1.8316e+01  1.8316e+01  2e-04  3e-06  1e-06  4e-07
 9:  1.8316e+01  1.8316e+01  3e-05  7e-07  3e-07  7e-08
10:  1.8316e+01  1.8316e+01  2e-06  4e-08  2e-08  2e-09
Optimal solution found.
-------------------------------------------------------------------------------
                                    Summary                                    
-------------------------------------------------------------------------------
(CVXPY) May 28 04:18:02 PM: Problem status: optimal
(CVXPY) May 28 04:18:02 PM: Optimal value: 1.832e+01
(CVXPY) May 28 04:18:02 PM: Compilation took 2.806e-02 seconds
(CVXPY) 

/Users/macbook/Desktop/PHD/CIKM/DAMR_CODE/FancyImpute.py:163: RuntimeWarning: divide by zero encountered in true_divide
  Sliding_mape= abs((np.array(Data_true)[missing_mask]-np.array(Data_Sliding)[missing_mask])/np.array(Data_true)[missing_mask]).mean()


# Run Baseline

In [5]:
#Create lags for the first variable.
#Extract the first variable
lags=30
var=0
Sliding_out_var1=Sliding_out[:,var,:]
Sliding_out_var1_sup=series_to_supervised(Sliding_out_var1,lags,1)
Sliding_out_var1_sup=Sliding_out_var1_sup.iloc[:,:lags*Sliding_out.shape[2]]
print(Sliding_out_var1_sup)
#Input1: 473*7*30
COVID_X1_all_aftslid=np.array(Sliding_out_var1_sup).reshape(len(Sliding_out_var1_sup),COVID_features.shape[2],lags)
#Input2: 473*3*7
COVID_features_aftslid=Sliding_out[30:,:,:]
#Input3: Adj: 473*7*7(Initialization)
Adj_all = np.arange(len(COVID_features_aftslid)*COVID_features_aftslid.shape[2]*COVID_features_aftslid.shape[2]).reshape(len(COVID_features_aftslid),COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2])#(473,7,7)
#Output:Groundtruth of the first variable->
COVID_Y1_all=COVID_features[30:,:,:]
COVID_Y1_all=COVID_Y1_all[:,var,:]
COVID_Y1_all=COVID_Y1_all.reshape(COVID_Y1_all.shape[0],COVID_Y1_all.shape[1],1)
#
print(COVID_X1_all_aftslid.shape,COVID_features_aftslid.shape,Adj_all.shape,COVID_Y1_all.shape)

    var1(t-30)  var2(t-30)  var3(t-30)  var4(t-30)  var5(t-30)  var6(t-30)  \
30   -0.588235   -0.795918   -0.111111   -0.423503   -0.894737    0.422222   
31   -0.647059   -0.755102    0.333333   -1.000000   -0.947368    0.666667   
32   -0.823529   -0.714286    0.333333   -0.707317   -0.842105    0.555556   
33   -0.705882   -0.591837   -0.111111   -0.902439   -0.736842    0.688889   
34   -0.411765   -0.428571   -0.555556   -0.804878   -0.736842    0.866667   
35   -0.411765   -0.543673   -0.111111   -0.658537   -0.684211    0.688889   
36   -0.352941   -0.224490   -0.111111   -0.121951   -0.473684    0.777778   
37   -0.235294   -0.142857   -0.111111   -0.268293   -0.842105    1.000000   
38   -0.117647   -0.469388    0.333333   -0.609756   -1.000000    0.955556   
39   -0.352941   -0.795918   -0.111111   -0.609756   -0.947368    0.822222   
40   -0.764706   -0.518367   -0.333333   -0.317073   -0.894737    0.777778   
41   -0.823529   -0.529499    0.111111   -0.414634   -0.842105  

In [6]:
type(Sliding_out_var1_sup)

pandas.core.frame.DataFrame

# 3.Dynamic Adjacency matrix layer

In [7]:
#3.1 Distance-based adjacency matrix 
#Country: BZ CL ID IR MX PR SA.
COVID_lat=pd.DataFrame([22.534241,22.491464,22.557269,22.563193,22.565809,22.603867,22.72016,22.528186,22.720358,22.630626])
COVID_long=pd.DataFrame([113.984871,113.94556,114.23687,114.106793,114.117757,114.267082,114.076601,114.496906,114.247468,114.423948])
Adj_dist=adj_dist(COVID_lat,COVID_long)#7*7

In [8]:
#3.2 Mean MI-based adjacency matrix
print(COVID_features_aftslid.shape)
MeanMI=[]
for i in range(COVID_features_aftslid.shape[2]):
    for j in range(COVID_features_aftslid.shape[2]):
        MeanMI.append(Global_MeanMI(COVID_features_aftslid[:,:,i],
                                    COVID_features_aftslid[:,:,j],2))
print(np.array(MeanMI).shape)
MeanMI=np.array(MeanMI).reshape(COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2])
print(MeanMI.shape)
scaler = MinMaxScaler(feature_range=(0, 1))
scaled1 = scaler.fit_transform(MeanMI)
MeanMI=scaled1#shape:7*7
print(MeanMI)

(21, 6, 10)
(100,)
(10, 10)
[[1.00000000e+00 3.05793685e-01 2.16684492e-02 5.68070304e-02
  5.50829645e-02 1.98417118e-02 2.24762904e-01 1.87220723e-01
  1.01210127e-01 1.01081526e-02]
 [3.35452251e-01 1.00000000e+00 2.06050002e-02 2.42810800e-02
  9.22419585e-04 0.00000000e+00 4.91483417e-02 1.11496360e-01
  5.81495408e-02 4.53907360e-02]
 [6.83920478e-03 2.27217921e-02 1.00000000e+00 6.35925815e-04
  2.52126734e-02 7.46684326e-03 4.47157191e-02 0.00000000e+00
  0.00000000e+00 6.48655462e-02]
 [9.31110893e-02 6.37469444e-02 3.72820519e-02 1.00000000e+00
  4.25279957e-02 4.25063803e-02 1.81406289e-03 7.20382406e-02
  4.17062564e-02 0.00000000e+00]
 [1.23751748e-01 7.22209300e-02 9.52012103e-02 7.04374031e-02
  1.00000000e+00 7.91227697e-02 4.83490190e-02 2.59063333e-01
  1.06664951e-01 4.38655850e-02]
 [0.00000000e+00 0.00000000e+00 4.21322839e-03 0.00000000e+00
  0.00000000e+00 1.00000000e+00 0.00000000e+00 6.16334637e-04
  3.55574328e-02 1.75916912e-02]
 [2.54629056e-01 9.08943038e-0

In [9]:
#3.3 CONCAT MI-based adjacency matrix
print(COVID_features_aftslid.shape)
ConcatMI=[]
for i in range(COVID_features_aftslid.shape[2]):
    for j in range(COVID_features_aftslid.shape[2]):
        ConcatMI.append(Global_MeanMI(COVID_features_aftslid[:,:,i],
                                    COVID_features_aftslid[:,:,j],2))
ConcatMI=np.array(ConcatMI).reshape(COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2])
scaler = MinMaxScaler(feature_range=(0, 1))
scaled1 = scaler.fit_transform(ConcatMI)
ConcatMI=scaled1#shape:7*7
print(ConcatMI)

(21, 6, 10)
[[1.00000000e+00 3.05793685e-01 2.16684492e-02 5.68070304e-02
  5.50829645e-02 1.98417118e-02 2.24762904e-01 1.87220723e-01
  1.01210127e-01 1.01081526e-02]
 [3.35452251e-01 1.00000000e+00 2.06050002e-02 2.42810800e-02
  9.22419585e-04 0.00000000e+00 4.91483417e-02 1.11496360e-01
  5.81495408e-02 4.53907360e-02]
 [6.83920478e-03 2.27217921e-02 1.00000000e+00 6.35925815e-04
  2.52126734e-02 7.46684326e-03 4.47157191e-02 0.00000000e+00
  0.00000000e+00 6.48655462e-02]
 [9.31110893e-02 6.37469444e-02 3.72820519e-02 1.00000000e+00
  4.25279957e-02 4.25063803e-02 1.81406289e-03 7.20382406e-02
  4.17062564e-02 0.00000000e+00]
 [1.23751748e-01 7.22209300e-02 9.52012103e-02 7.04374031e-02
  1.00000000e+00 7.91227697e-02 4.83490190e-02 2.59063333e-01
  1.06664951e-01 4.38655850e-02]
 [0.00000000e+00 0.00000000e+00 4.21322839e-03 0.00000000e+00
  0.00000000e+00 1.00000000e+00 0.00000000e+00 6.16334637e-04
  3.55574328e-02 1.75916912e-02]
 [2.54629056e-01 9.08943038e-02 8.67262248e-02

In [10]:
#3.4 Single Feature MI-based adjacency matrix
COVID_features_aftslid.shape
FeatureMI=[]
for i in range(COVID_features_aftslid.shape[2]):
    for j in range(COVID_features_aftslid.shape[2]):
        FeatureMI.append(Global_EachMI(COVID_features_aftslid[:,:,i],
                                    COVID_features_aftslid[:,:,j],2))
#For the first feature,if choose the second feature, modify here!!
FeatureMI=np.array(FeatureMI)[:,2]
FeatureMI=np.array(FeatureMI).reshape(COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2])
scaler = MinMaxScaler(feature_range=(0, 1))
scaled1 = scaler.fit_transform(FeatureMI)
FeatureMI=scaled1#shape:7*7
#MeanMI,ConcatMI,FeatureMI

In [11]:
#3.5 Mean MI-based dynamic adjacency matrix
print(COVID_features_aftslid.shape)
#Index all of the rows and columns
DyMeanMI=[]
for k in range(COVID_features_aftslid.shape[0]):
    for i in range(COVID_features_aftslid.shape[2]):
        for j in range(COVID_features_aftslid.shape[2]):
            DyMeanMI.append(Global_MeanMI(COVID_features_aftslid[:k,:,i],
                                    COVID_features_aftslid[:k,:,j],2))
DyMeanMI=np.array(DyMeanMI).reshape(COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[0])
DyMeanMI=DyMeanMI.transpose(2, 0, 1)
from fancyimpute import SimpleFill, NuclearNormMinimization, SoftImpute, BiScaler
for i in range(DyMeanMI.shape[0]):
    MEAN_imputer = SimpleFill()
    DyMeanMI[i,:,:]=MEAN_imputer.fit_transform(DyMeanMI[i,:,:])
print(DyMeanMI)#Here DyMeanMI is done

(21, 6, 10)


/Users/macbook/Desktop/PHD/CIKM/DAMR_CODE/model.py:67: RuntimeWarning: invalid value encountered in true_divide
  c_normalized = c / float(np.sum(c))


[[[0.23641487 0.29562816 0.27969635 ... 0.         0.         0.        ]
  [0.83333333 0.83333333 0.83333333 ... 0.32080208 0.47385139 0.91829583]
  [0.44649115 0.1760651  0.31127812 ... 0.25395809 0.88794309 0.20305678]
  ...
  [0.18988292 0.14747639 0.05881056 ... 0.13863673 0.09862709 0.10587228]
  [0.05783821 0.28483904 0.73836917 ... 0.09805162 0.12220737 0.0801271 ]
  [0.06940957 0.73927602 0.02095276 ... 0.10365595 0.05640263 0.08020674]]

 [[0.2175186  0.24760823 0.30197307 ... 0.         0.         0.        ]
  [0.83333333 1.         0.83333333 ... 0.54302431 0.5849625  0.84273177]
  [0.20751875 0.4260651  0.19649115 ... 0.25395809 0.17095059 0.15943066]
  ...
  [0.11972745 0.16215998 0.11816491 ... 0.0146342  0.08844794 0.20077799]
  [0.0146342  0.07293147 0.02870075 ... 0.03702053 0.09309624 0.21134325]
  [0.11036752 0.06034206 0.81190019 ... 0.10006053 0.09455674 0.10671533]]

 [[0.27488    0.23376133 0.26487722 ... 0.         0.         0.        ]
  [0.83333333 1.      

In [15]:
#3.6 Concat MI-based dynamic adjacency matrix
#Index all of the rows and columns
DyConcatMI=[]
for k in range(COVID_features_aftslid.shape[0]):
    for i in range(COVID_features_aftslid.shape[2]):
        for j in range(COVID_features_aftslid.shape[2]):
            DyConcatMI.append(Global_MeanMI(COVID_features_aftslid[:k,:,i],
                                    COVID_features_aftslid[:k,:,j],2))
DyConcatMI=np.array(DyConcatMI).reshape(COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[0])
DyConcatMI=DyConcatMI.transpose(2, 0, 1)
from fancyimpute import SimpleFill, NuclearNormMinimization, SoftImpute, BiScaler
for i in range(DyConcatMI.shape[0]):
    MEAN_imputer = SimpleFill()
    DyConcatMI[i,:,:]=MEAN_imputer.fit_transform(DyConcatMI[i,:,:])
print(DyConcatMI.shape)#Here DyConcatMI is done

/Users/macbook/Desktop/PHD/CIKM/DAMR_CODE/model.py:67: RuntimeWarning: invalid value encountered in true_divide
  c_normalized = c / float(np.sum(c))


(21, 10, 10)


In [13]:
#3.7 FFT-based sum batch's MI dynamic adjacency matrix
print(COVID_features_aftslid.shape)
T=[20,40,100];
Term1=T[0]
Term2=T[1]
Term3=T[2]
#Step1: Calculate Adj in each batch
#(1) Term1
a=[]
from math import ceil#Eg:Ceil(2.2)=3
for i in range(COVID_features_aftslid.shape[2]):
    for j in range(COVID_features_aftslid.shape[2]):
        for k in np.arange(ceil(COVID_features_aftslid.shape[0]/Term1)):
            a.append(Global_MeanMI(COVID_features_aftslid[k*Term1:k*Term1+Term1,:,i],COVID_features_aftslid[k*Term1:k*Term1+Term1,:,j],2))
a=np.array(a).reshape(COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2],ceil(COVID_features_aftslid.shape[0]/Term1))#a:(7, 7, 23)
a=a.transpose(2,0,1)
print(a.shape)#(24,7,7)

#(2) Term2
b=[]
for i in range(COVID_features_aftslid.shape[2]):
    for j in range(COVID_features_aftslid.shape[2]):
        for k in np.arange(ceil(COVID_features_aftslid.shape[0]/Term2)):
            b.append(Global_MeanMI(COVID_features_aftslid[k*Term2:k*Term2+Term2,:,i],COVID_features_aftslid[k*Term2:k*Term2+Term2,:,j],2))
b=np.array(b).reshape(COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2],ceil(COVID_features_aftslid.shape[0]/Term2))#a:(7, 7, 23)
print(b.shape)#(7, 7, 12)
b=b.transpose(2,0,1)
print(b.shape)#(12,7,7)

#(3) Term3
c=[]
for i in range(COVID_features_aftslid.shape[2]):
    for j in range(COVID_features_aftslid.shape[2]):
        for k in np.arange(ceil(COVID_features_aftslid.shape[0]/Term3)):
            c.append(Global_MeanMI(COVID_features_aftslid[k*Term3:k*Term3+Term3,:,i],COVID_features_aftslid[k*Term3:k*Term3+Term3,:,j],2))
c=np.array(c).reshape(COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2],ceil(COVID_features_aftslid.shape[0]/Term3))#a:(7, 7, 23)
print(c.shape)#(7, 7, 5)
c=c.transpose(2,0,1)
print(c.shape)#(5,7,7)
#Step2:Assign it to particular position:
#Each timestamp from the same batch share the same Adj.
#MeanMI
data=[]
for j in range(a.shape[0]):
    for i in range(Term1):
        data.append(a[j,:,:])
data=np.array(data)
test=data
DyConcatMI1=test[:DyConcatMI.shape[0],:,:]
print(DyConcatMI1.shape)#(473,7,7)

data=[]
for j in range(b.shape[0]):
    for i in range(Term2):
        data.append(b[j,:,:])
data=np.array(data)
test=data
DyConcatMI2=test[:DyConcatMI.shape[0],:,:]
print(DyConcatMI2.shape)#(473,7,7)

data=[]
for j in range(c.shape[0]):
    for i in range(Term3):
        data.append(c[j,:,:])
data=np.array(data)
test=data
DyConcatMI3=test[:DyConcatMI.shape[0],:,:]
print(DyConcatMI3.shape)#(473,7,7)

# Step3: Add all of the adjacency matrices
DyConcatFFTMI=DyConcatMI1+DyConcatMI2+DyConcatMI3
print(DyConcatFFTMI.shape)#(473,7,7)

# Step4: Normalize adjacency matrices
from sklearn.preprocessing import MinMaxScaler
for i in range(DyConcatFFTMI.shape[0]):
    scaler = MinMaxScaler(feature_range=(0, 1))
    DyConcatFFTMI[i,:,:] = scaler.fit_transform(DyConcatFFTMI[i,:,:])
print(DyConcatFFTMI)

(21, 6, 10)
(2, 10, 10)
(10, 10, 1)
(1, 10, 10)
(10, 10, 1)
(1, 10, 10)
(21, 10, 10)
(21, 10, 10)
(21, 10, 10)
(21, 10, 10)
[[[1.         0.30426996 0.02994476 ... 0.18826862 0.095912   0.00411109]
  [0.33283688 1.         0.02825482 ... 0.10133395 0.05412026 0.04306869]
  [0.00543871 0.02707526 1.         ... 0.         0.         0.07006404]
  ...
  [0.27705971 0.15754343 0.04284977 ... 1.         0.10624294 0.01031106]
  [0.11208695 0.0674958  0.00186946 ... 0.07827561 1.         0.17589547]
  [0.0491525  0.10724279 0.14069841 ... 0.02693384 0.20335803 1.        ]]

 [[1.         0.30426996 0.02994476 ... 0.18826862 0.095912   0.00411109]
  [0.33283688 1.         0.02825482 ... 0.10133395 0.05412026 0.04306869]
  [0.00543871 0.02707526 1.         ... 0.         0.         0.07006404]
  ...
  [0.27705971 0.15754343 0.04284977 ... 1.         0.10624294 0.01031106]
  [0.11208695 0.0674958  0.00186946 ... 0.07827561 1.         0.17589547]
  [0.0491525  0.10724279 0.14069841 ... 0.026933

In [14]:
#3.8 FFT-based MI-based dynamic adjacency matrix
print(COVID_features_aftslid.shape)
T=[20,40,100];
Term1=T[0]
Term2=T[1]
Term3=T[2]

#Step1: Calculate Adj in each batch

#(1) Term1
a=[]
from math import ceil#Eg:Ceil(2.2)=3
for i in range(COVID_features_aftslid.shape[2]):
    for j in range(COVID_features_aftslid.shape[2]):
        for k in np.arange(ceil(COVID_features_aftslid.shape[0]/Term1)):
            a.append(Global_MeanMI(COVID_features_aftslid[k*Term1:k*Term1+Term1,:,i],COVID_features_aftslid[k*Term1:k*Term1+Term1,:,j],2))
a=np.array(a).reshape(COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2],ceil(COVID_features_aftslid.shape[0]/Term1))#a:(7, 7, 23)
a=a.transpose(2,0,1)
print(a.shape)#(24,7,7)

#(2) Term2
b=[]
for i in range(COVID_features_aftslid.shape[2]):
    for j in range(COVID_features_aftslid.shape[2]):
        for k in np.arange(ceil(COVID_features_aftslid.shape[0]/Term2)):
            b.append(Global_MeanMI(COVID_features_aftslid[k*Term2:k*Term2+Term2,:,i],COVID_features_aftslid[k*Term2:k*Term2+Term2,:,j],2))
b=np.array(b).reshape(COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2],ceil(COVID_features_aftslid.shape[0]/Term2))#a:(7, 7, 23)
print(b.shape)#(7, 7, 12)
b=b.transpose(2,0,1)
print(b.shape)#(12,7,7)

#(3) Term3
c=[]
for i in range(COVID_features_aftslid.shape[2]):
    for j in range(COVID_features_aftslid.shape[2]):
        for k in np.arange(ceil(COVID_features_aftslid.shape[0]/Term3)):
            c.append(Global_MeanMI(COVID_features_aftslid[k*Term3:k*Term3+Term3,:,i],COVID_features_aftslid[k*Term3:k*Term3+Term3,:,j],2))
c=np.array(c).reshape(COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2],ceil(COVID_features_aftslid.shape[0]/Term3))#a:(7, 7, 23)
print(c.shape)#(7, 7, 5)
c=c.transpose(2,0,1)
print(c.shape)#(5,7,7)
#Step2: Calculate MI's MI for periodic term 1
#Term1
temp=[]
for j in range(a.shape[0]):
    for i in range(a.shape[0]):
        temp.append(Global_MeanMI(a[j,:,:],a[i,:,:],2))#The first point MI's MI 
temp=np.array(temp).reshape(a.shape[0],a.shape[0])#24*24

#Step3: Weighted sum for the same periodic term
index_all=np.arange(temp.shape[0]*temp.shape[0]).reshape(a.shape[0],a.shape[0])#Initialization of index_all,shape=24*24
for i in range(temp.shape[0]):
    arrIndex=temp[i,:].argsort()
    temp[i,:]=temp[i,:][arrIndex[::-1]]
    index_all[i,:]=arrIndex
print(temp.shape)#24*24
print(index_all.shape)#24*24

all_term=5#Get the first 5 decomposition
a_all=np.zeros((a.shape[0],COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2]))
for i in range(a.shape[0]):
    for u in range(all_term):
        a_all[i,:,:]=a_all[i,:,:]+a[i,:,:]+index_all[i,u]*temp[i,u]
print(a_all.shape)#(24,7,7)

#Step2: Calculate MI's MI for periodic term 2
#Term2
temp=[]
for j in range(b.shape[0]):
    for i in range(b.shape[0]):
        temp.append(Global_MeanMI(b[j,:,:],b[i,:,:],2))#The first point MI's MI 
temp=np.array(temp).reshape(b.shape[0],b.shape[0])#12*12

#Step3: Weighted sum for the same periodic term
index_all=np.arange(temp.shape[0]*temp.shape[0]).reshape(b.shape[0],b.shape[0])#Initialization of index_all,shape=24*24
for i in range(temp.shape[0]):
    arrIndex=temp[i,:].argsort()
    temp[i,:]=temp[i,:][arrIndex[::-1]]
    index_all[i,:]=arrIndex
print(temp.shape)#12*12
print(index_all.shape)#12*12

all_term=5#Get the first 5 decomposition
b_all=np.zeros((b.shape[0],COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2]))
for i in range(b.shape[0]):
    for u in range(all_term):
        b_all[i,:,:]=b_all[i,:,:]+b[i,:,:]+index_all[i,u]*temp[i,u]
print(b_all.shape)#(12,7,7)

#Step2: Calculate MI's MI for periodic term 3
#Term3
temp=[]
for j in range(c.shape[0]):
    for i in range(c.shape[0]):
        temp.append(Global_MeanMI(c[j,:,:],c[i,:,:],2))#The first point MI's MI 
temp=np.array(temp).reshape(c.shape[0],c.shape[0])#12*12

#Step3: Weighted sum for the same periodic term
index_all=np.arange(temp.shape[0]*temp.shape[0]).reshape(c.shape[0],c.shape[0])#Initialization of index_all,shape=24*24
for i in range(temp.shape[0]):
    arrIndex=temp[i,:].argsort()
    temp[i,:]=temp[i,:][arrIndex[::-1]]
    index_all[i,:]=arrIndex
print(temp.shape)#5*5
print(index_all.shape)#5*5

all_term=5#Get the first 5 decomposition
c_all=np.zeros((c.shape[0],COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2]))
for i in range(c.shape[0]):
    for u in range(all_term):
        c_all[i,:,:]=c_all[i,:,:]+c[i,:,:]+index_all[i,u]*temp[i,u]
print(c_all.shape)#(5,7,7)

#Step4:Assign it to particular position:
#Each timestamp from the same batch share the same Adj.
#MeanMI
data=[]
for j in range(a_all.shape[0]):
    for i in range(Term1):
        data.append(a_all[j,:,:])
data=np.array(data)
test=data
DyConcatMI1=test[:DyConcatMI.shape[0],:,:]
print(DyConcatMI1.shape)#(473,7,7)

data=[]
for j in range(b_all.shape[0]):
    for i in range(Term2):
        data.append(b_all[j,:,:])
data=np.array(data)
test=data
DyConcatMI2=test[:DyConcatMI.shape[0],:,:]
print(DyConcatMI2.shape)#(473,7,7)

data=[]
for j in range(c_all.shape[0]):
    for i in range(Term3):
        data.append(c_all[j,:,:])
data=np.array(data)
test=data
DyConcatMI3=test[:DyConcatMI.shape[0],:,:]
print(DyConcatMI3.shape)#(473,7,7)

# Step5: Add all of the adjacency matrices
DyConcatFFTeachMI=DyConcatMI1+DyConcatMI2+DyConcatMI3
print(DyConcatFFTeachMI.shape)#(473,7,7)

# Step6: Normalize adjacency matrices
from sklearn.preprocessing import MinMaxScaler
for i in range(DyConcatFFTeachMI.shape[0]):
    scaler = MinMaxScaler(feature_range=(0, 1))
    DyConcatFFTeachMI[i,:,:] = scaler.fit_transform(DyConcatFFTeachMI[i,:,:])
print(DyConcatFFTeachMI)


(21, 6, 10)
(2, 10, 10)
(10, 10, 1)
(1, 10, 10)
(10, 10, 1)
(1, 10, 10)
(2, 2)
(2, 2)


IndexError: index 2 is out of bounds for axis 1 with size 2

In [ ]:
print(COVID_features_aftslid.shape)#473*3*7
print(COVID_X1_all_aftslid.shape)#473*7*30
print(COVID_Y1_all.shape)#(473, 7, 1)
print(Adj_dist.shape)#7*7
# Set Hyperpaprameters
tf.keras.backend.clear_session()#clear all
tf.autograph.set_verbosity(0)#reset to zero
learning_rate = 0.0001
batch_size =24
epochs = 100
seed = 42
verbose = 1

In [ ]:
## Define Model
inputs_ret = Input(shape=(COVID_X1_all_aftslid.shape[1], COVID_X1_all_aftslid.shape[2], ))#7*30=node*lags(Time to look back)
inputs_feat = Input(shape=(COVID_features_aftslid.shape[2], COVID_features_aftslid.shape[1], ))#7*6=Node*feature
inputs_adj = Input(shape=(Adj_dist.shape[1],Adj_dist.shape[1], ))#7*7=node*node
print(inputs_ret.shape)
print(inputs_feat.shape)
print(inputs_adj.shape)

In [ ]:
#GATinput:1.input nodes*lags 2.adj:nodes*nodes
#GAToutput:1.channels*att_heads2.Att_weights=nodes*heads*nodes
GAT_output_P, Att_weights_P =  GATConv(16, attn_heads=4, concat_heads=True, dropout_rate=0.3, return_attn_coef=True, 
                                   activation='relu', use_bias=False)([inputs_ret, inputs_adj])

In [ ]:
Att_weights_P = tf.math.reduce_mean(Att_weights_P, axis=2)#reduce heads,it will be nodes*nodes
print(Att_weights_P)

In [ ]:
GCN_output_P =  GCNConv(16, dropout_rate=0.3, 
                        activation='relu', use_bias=True)([inputs_feat, inputs_adj])

In [ ]:
diff_out = DiffusionConv(16, K=6, activation='tanh')([inputs_feat, Att_weights_P])#diff_out=nodes*channels

In [ ]:
con_out_P_2 = Concatenate(axis=-1)([GAT_output_P, GCN_output_P,diff_out])
dense_P = Dense(8, activation='relu')(con_out_P_2)

In [ ]:
dense_out = Dropout(0.2)(dense_P)
outputs = Dense(1)(dense_out)



In [ ]:
model = Model(inputs=[inputs_ret, inputs_feat, inputs_adj], outputs=outputs)
model.compile(optimizer=Adam(learning_rate=learning_rate), loss='mse', metrics=["mae", "mape"])
model.summary()

In [ ]:
#Get 473*7*7 Adj_dist
Adj_dist=adj_dist(COVID_lat,COVID_long)#7*7
Adj_dist=pd.DataFrame(Adj_dist)
Adj_all = np.arange(473*7*7).reshape(473,7,7)#(473,7,7)
Adj_all[0,:,:]=pd.DataFrame(Adj_all[0,:,:])
Adj_all[0,:,:]=Adj_dist
data=[]
for i in range(Adj_all.shape[0]):
    data.append(Adj_dist)
data=np.array(data)
Adj_dist=data
#MeanMI
Adj_MeanMI=MeanMI
Adj_all = np.arange(473*7*7).reshape(473,7,7)#(473,7,7)
Adj_all[0,:,:]=pd.DataFrame(Adj_all[0,:,:])
Adj_all[0,:,:]=MeanMI
data=[]
for i in range(Adj_all.shape[0]):
    data.append(Adj_MeanMI)
data=np.array(data)
Adj_MeanMI=data
#ConcatMI
Adj_ConcatMI=ConcatMI
Adj_all = np.arange(473*7*7).reshape(473,7,7)#(473,7,7)
Adj_all[0,:,:]=pd.DataFrame(Adj_all[0,:,:])
Adj_all[0,:,:]=Adj_ConcatMI
data=[]
for i in range(Adj_all.shape[0]):
    data.append(Adj_ConcatMI)
data=np.array(data)
Adj_ConcatMI=data
#FeatureMI
Adj_FeatureMI=FeatureMI
Adj_all = np.arange(473*7*7).reshape(473,7,7)#(473,7,7)
Adj_all[0,:,:]=pd.DataFrame(Adj_all[0,:,:])
Adj_all[0,:,:]=Adj_FeatureMI
data=[]
for i in range(Adj_all.shape[0]):
    data.append(Adj_FeatureMI)
data=np.array(data)
Adj_FeatureMI=data


In [ ]:
# #DyMeanMI
# #3.2 Mean MI-based dynamic adjacency matrix
# print(COVID_features_aftslid.shape)#(473, 3, 7)
# #Index all of the rows and columns
# MeanMI=[]
# for k in range(COVID_features_aftslid.shape[0]):
#     for i in range(COVID_features_aftslid.shape[2]):
#         for j in range(COVID_features_aftslid.shape[2]):
#             MeanMI.append(Global_MeanMI(COVID_features_aftslid[:k,:,i],
#                                     COVID_features_aftslid[:k,:,j],2))
# DyMeanMI=np.array(MeanMI).reshape(COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[2],COVID_features_aftslid.shape[0])
# DyMeanMI=DyMeanMI.transpose(2, 0, 1)
# print(DyMeanMI.shape)#(473,7,7)

In [ ]:

print(COVID_features_aftslid.shape)#473*3*7
COVID_features_aftslid= np.transpose(COVID_features_aftslid,(0,2,1))#473*7*3
print(COVID_X1_all_aftslid.shape)#473*7*30
print(np.array(COVID_Y1_all).shape)#(473, 7, 1)
print(np.array(Adj_MeanMI).shape)#473*7*7
#Normalization
scaler = MinMaxScaler(feature_range=(-1, 1))
scaled1 = scaler.fit_transform(COVID_Y1_all[:,:,0])
COVID_Y1_all[:,:,0]=scaled1


In [ ]:
x_train=COVID_X1_all_aftslid[:int(len(COVID_X1_all_aftslid)*0.8),:,:]
x_val=COVID_X1_all_aftslid[int(len(COVID_X1_all_aftslid)*0.8):int(len(COVID_X1_all_aftslid)*0.9),:,:]
x_test=COVID_X1_all_aftslid[int(len(COVID_X1_all_aftslid)*0.9):,:,:]
features_train=COVID_features_aftslid[:int(len(COVID_features_aftslid)*0.8),:,:]
features_val=COVID_features_aftslid[int(len(COVID_features_aftslid)*0.8):int(len(COVID_features_aftslid)*0.9),:,:]
features_test=COVID_features_aftslid[int(len(COVID_features_aftslid)*0.9):,:,:]
adj_train=DyConcatMI[:int(len(DyConcatMI)*0.8),:,:]
adj_val=DyConcatMI[int(len(DyConcatMI)*0.8):int(len(DyConcatMI)*0.9),:,:]
adj_test=DyConcatMI[int(len(DyConcatMI)*0.9):,:,:]
y_train=COVID_Y1_all[:int(len(COVID_Y1_all)*0.8),:,:]
y_val=COVID_Y1_all[int(len(COVID_Y1_all)*0.8):int(len(COVID_Y1_all)*0.9),:,:]
y_test=COVID_Y1_all[int(len(COVID_Y1_all)*0.9):,:,:]

In [ ]:
print(x_train.shape)
print(features_train.shape)
print(adj_train.shape)
print(y_train.shape)

In [ ]:
tf.config.experimental_run_functions_eagerly(True)
# Set Hyperpaprameters
tf.keras.backend.clear_session()#clear all
tf.autograph.set_verbosity(0)#reset to zero


# hists = model.fit(x= [x_train, features_train, adj_train],
#                   y= y_train, verbose=verbose, epochs=500,
#                   batch_size=batch_size, #validation_split=0.1, 
#                   validation_data=([x_val, features_val, adj_val], y_val),
#                   #test_data=([x_test, features_test, adj_test], y_test),
#   )

##If you want to train faster, try earlystopping.

hists = model.fit(x= [x_train, features_train, adj_train],
                  y= y_train, verbose=verbose, epochs=500,
                  batch_size=batch_size, #validation_split=0.1, 
                  validation_data=([x_val, features_val, adj_val], y_val),
                  #test_data=([x_test, features_test, adj_test], y_test),
                    callbacks=[EarlyStopping(#monitor="val_mean_absolute_error", 
                      monitor="val_loss", patience=20, restore_best_weights=True)],
  )


In [ ]:
def mae(y_true, y_pred):
    return np.mean(np.abs(y_pred - y_true))

def rmse(y_true, y_pred):
    return np.sqrt(np.mean(np.square(y_pred - y_true)))

def mape(y_true, y_pred, threshold=0.1):
    v = np.clip(np.abs(y_true), threshold, None)
    diff = np.abs((y_true - y_pred) / v)
    return np.mean(diff, axis=-1).mean()
###Write the function of mre
def mre(y_true, y_pred):
    return np.sum(np.abs(y_pred - y_true))/np.sum(np.abs(y_true))
def get_metrics(y, yp):
    return {

        "mae": np.round(mae(y, yp), 4),
        "mape": np.round(mape(y, yp),4),
        "mre": np.round(mre(y, yp),4),
        "rmse": np.round(rmse(y, yp), 4),
        #"MPE": np.round(MPE(y, yp), 4),
        #"R2": np.round(R_squared(y, yp),4)   
    }

# scaled1 = scaler.fit_transform(MeanMI)
#Get the tensor of test set after masking it.
test_predicted = model.predict([x_test, features_test, adj_test])
get_metrics(y_test.flatten(), test_predicted.flatten())


In [ ]:
#Get the mask of y_test.
Mask_BZ=pd.read_csv("Data/COVID/10%/BZ_10.csv")
Mask_CL=pd.read_csv("Data/COVID/10%/CL_10.csv")
Mask_ID=pd.read_csv("Data/COVID/10%/ID_10.csv")
Mask_IR=pd.read_csv("Data/COVID/10%/IR_10.csv")
Mask_MX=pd.read_csv("Data/COVID/10%/MX_10.csv")
Mask_PR=pd.read_csv("Data/COVID/10%/PR_10.csv")
Mask_SA=pd.read_csv("Data/COVID/10%/SA_10.csv")

In [ ]:
Mask_BZ=np.array(Mask_BZ)
missing_mask=[]
for i in range(Mask_BZ.shape[0]):
    missing_mask.append(np.isnan(np.array(Mask_BZ[i])))
missing_mask=np.array(missing_mask).reshape(Mask_BZ.shape[0],Mask_BZ.shape[1])
missing_mask_BZ_test=missing_mask[-15-y_test.shape[0]:-15,:]#48*3
#Get the first feature's mask of BZ
missing_mask_BZ_test1=missing_mask_BZ_test[:,0]

In [ ]:
Mask_CL=np.array(Mask_CL)
missing_mask=[]
for i in range(Mask_CL.shape[0]):
    missing_mask.append(np.isnan(np.array(Mask_CL[i])))
missing_mask=np.array(missing_mask).reshape(Mask_CL.shape[0],Mask_CL.shape[1])
missing_mask_CL_test=missing_mask[-15-y_test.shape[0]:-15,:]#48*3
#Get the first feature's mask of CL
missing_mask_CL_test1=missing_mask_CL_test[:,0]
Mask_ID=np.array(Mask_ID)
missing_mask=[]
for i in range(Mask_ID.shape[0]):
    missing_mask.append(np.isnan(np.array(Mask_ID[i])))
missing_mask=np.array(missing_mask).reshape(Mask_ID.shape[0],Mask_ID.shape[1])
missing_mask_ID_test=missing_mask[-15-y_test.shape[0]:-15,:]#48*3
#Get the first feature's mask of ID
missing_mask_ID_test1=missing_mask_ID_test[:,0]
Mask_IR=np.array(Mask_IR)
missing_mask=[]
for i in range(Mask_IR.shape[0]):
    missing_mask.append(np.isnan(np.array(Mask_IR[i])))
missing_mask=np.array(missing_mask).reshape(Mask_IR.shape[0],Mask_IR.shape[1])
missing_mask_IR_test=missing_mask[-15-y_test.shape[0]:-15,:]#48*3
#Get the first feature's mask of IR
missing_mask_IR_test1=missing_mask_IR_test[:,0]
Mask_MX=np.array(Mask_MX)
missing_mask=[]
for i in range(Mask_MX.shape[0]):
    missing_mask.append(np.isnan(np.array(Mask_MX[i])))
missing_mask=np.array(missing_mask).reshape(Mask_MX.shape[0],Mask_MX.shape[1])
missing_mask_MX_test=missing_mask[-15-y_test.shape[0]:-15,:]#48*3
#Get the first feature's mask of MX
missing_mask_MX_test1=missing_mask_MX_test[:,0]
Mask_PR=np.array(Mask_PR)
missing_mask=[]
for i in range(Mask_PR.shape[0]):
    missing_mask.append(np.isnan(np.array(Mask_PR[i])))
missing_mask=np.array(missing_mask).reshape(Mask_PR.shape[0],Mask_PR.shape[1])
missing_mask_PR_test=missing_mask[-15-y_test.shape[0]:-15,:]#48*3
#Get the first feature's mask of PR
missing_mask_PR_test1=missing_mask_PR_test[:,0]
Mask_SA=np.array(Mask_SA)
missing_mask=[]
for i in range(Mask_SA.shape[0]):
    missing_mask.append(np.isnan(np.array(Mask_SA[i])))
missing_mask=np.array(missing_mask).reshape(Mask_SA.shape[0],Mask_SA.shape[1])
missing_mask_SA_test=missing_mask[-15-y_test.shape[0]:-15,:]#48*3
#Get the first feature's mask of SA
missing_mask_SA_test1=missing_mask_SA_test[:,0]

In [ ]:
missing_mask_ALL_test1=np.stack((missing_mask_BZ_test1,missing_mask_CL_test1
            ,missing_mask_ID_test1,missing_mask_IR_test1,
            missing_mask_MX_test1,missing_mask_PR_test1,missing_mask_SA_test1
           ),axis=1)

In [ ]:
#Get test set result.
get_metrics(y_test[missing_mask_ALL_test1].flatten(), test_predicted[missing_mask_ALL_test1].flatten())